CREATE TABLE `duration` (`Id` int NOT NULL, `start_time` time, `end_time` time, PRIMARY KEY (`Id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `duration` (`Id`, `start_time`, `end_time`) VALUES (1, '09:00:00', '09:30:00');
INSERT INTO `duration` (`Id`, `start_time`, `end_time`) VALUES (2, '09:30:00', '10:00:00');
INSERT INTO `duration` (`Id`, `start_time`, `end_time`) VALUES (3, '10:00:00', '10:30:00');
INSERT INTO `duration` (`Id`, `start_time`, `end_time`) VALUES (4, '10:30:00', '11:00:00');
CREATE TABLE `meeting_room_details` (`id` int NOT NULL AUTO_INCREMENT, `capacity` int, `floor` int, `location` varchar(255), `name` varchar(255), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `meeting_room_details` (`id`, `capacity`, `floor`, `location`, `name`) VALUES (1, 10, 1, 'Bexhill', 'Newton');
INSERT INTO `meeting_room_details` (`id`, `capacity`, `floor`, `location`, `name`) VALUES (2, 5, 2, 'Bexhill', 'Einstein');
INSERT INTO `meeting_room_details` (`id`, `capacity`, `floor`, `location`, `name`) VALUES (3, 4, 2, 'Derbyshire', 'Abdul Kalam');
CREATE TABLE `scheduler` (`id` int NOT NULL AUTO_INCREMENT, `event_name` varchar(255), `owner` int, `meeting_room_details_id` int, `duration_id` int, `schedule_date` date, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `scheduler` (`id`, `event_name`, `owner`, `meeting_room_details_id`, `duration_id`, `schedule_date`) VALUES (1, 'Code Review', 1, 1, 1, '2019-10-10');
INSERT INTO `scheduler` (`id`, `event_name`, `owner`, `meeting_room_details_id`, `duration_id`, `schedule_date`) VALUES (2, 'Stand Up Meeting', 1, 1, 2, '2019-10-10');
INSERT INTO `scheduler` (`id`, `event_name`, `owner`, `meeting_room_details_id`, `duration_id`, `schedule_date`) VALUES (3, 'Retrospective', 1, 1, 3, '2019-10-10');
CREATE TABLE `schedules_user` (`schedules_id` int NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`schedules_id`, `user_id`), INDEX `FKnokmjoqthg2usxg5vw5x8yq6s` (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `schedules_user` (`schedules_id`, `user_id`) VALUES (1, 1);
INSERT INTO `schedules_user` (`schedules_id`, `user_id`) VALUES (2, 1);
CREATE TABLE `user` (`id` bigint NOT NULL AUTO_INCREMENT, `email` varchar(200) NOT NULL, `user_password` varchar(255), `first_name` varchar(255), `last_name` varchar(255), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `user` (`id`, `email`, `user_password`, `first_name`, `last_name`) VALUES (1, 'admin@gmail.com', 'admin', 'Rob', 'Synth');
INSERT INTO `user` (`id`, `email`, `user_password`, `first_name`, `last_name`) VALUES (2, 'pratik@gmail.com', 'pratik', 'Pratik', 'Bhatt');
INSERT INTO `user` (`id`, `email`, `user_password`, `first_name`, `last_name`) VALUES (3, 'diwakar@gmail.com', 'diwakar', 'Diwakar', 'Labh');
ALTER TABLE `schedules_user` ADD CONSTRAINT `FKjkpiofgq6sq0dhfo1v6qgga75` FOREIGN KEY (`schedules_id`) REFERENCES `scheduler` (`id`) ;
ALTER TABLE `schedules_user` ADD CONSTRAINT `FKnokmjoqthg2usxg5vw5x8yq6s` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);